; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Secure Delete Interface"
#define MyAppVersion "1.0.0-beta"
#define MyAppPublisher "Yalla Nkardaz"
#define MyAppURL "https://github.com/DemerNkardaz/SDeleteGUI"
#define MyAppExeName "SDeleteGUI.exe"

; ============================================================
; Architecture selection.
; Compile with: iscc installer.iss
;   -> x64 build (default)
; Compile with: iscc /DAppArchitecture=arm64 installer.iss
;   -> ARM64 build
; ============================================================
#ifndef AppArchitecture
  #define AppArchitecture "x64"
#endif

#if AppArchitecture == "x64"
  #define InstallArchitecture "x64compatible"
  #define PublishDir "..\bin\Release\net10.0-windows10.0.26100.0\win-x64\publish"
  #define OutputName "SDeleteGUIx64_Setup"
#elif AppArchitecture == "arm64"
  #define InstallArchitecture "arm64"
  #define PublishDir "..\bin\Release\net10.0-windows10.0.26100.0\win-arm64\publish"
  #define OutputName "SDeleteGUIARM_Setup"
#else
  #error AppArchitecture must be either "x64" or "arm64"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{600BB1F7-1DAD-4B10-B134-F645C0638F0A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Nkardaz\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; Architecture-specific settings come from the #if block above.
ArchitecturesAllowed={#InstallArchitecture}
ArchitecturesInstallIn64BitMode={#InstallArchitecture}
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename={#OutputName}
SolidCompression=yes
WizardStyle=modern dynamic windows11
SetupIconFile=..\Assets\AppIcon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PublishDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
; --- Files ---
Root: HKCU; Subkey: "Software\Classes\*\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Безопасно удалить"; Languages: russian; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Secure delete"; Languages: english; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName}"; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MultiSelectModel"; ValueData: "Single"; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\*\shell\Nkardaz.SDeleteGUI\command"; ValueType: string; \
    ValueData: """{app}\{#MyAppExeName}"" ""%1"""; \
    Flags: uninsdeletekey

; --- Directories ---
Root: HKCU; Subkey: "Software\Classes\Directory\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Безопасно удалить"; Languages: russian; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Secure delete"; Languages: english; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName}"; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MultiSelectModel"; ValueData: "Single"; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\shell\Nkardaz.SDeleteGUI\command"; ValueType: string; \
    ValueData: """{app}\{#MyAppExeName}"" ""%1"""; \
    Flags: uninsdeletekey

; --- Directory background (empty space inside folder) ---
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Очистить свободное место"; Languages: russian; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Clean free space"; Languages: english; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\SDeleteGUI"; ValueType: string; \
    ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName}"; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\SDeleteGUI\command"; ValueType: string; \
    ValueData: """{app}\{#MyAppExeName}"" ""%V"""; \
    Flags: uninsdeletekey

; --- Drives ---
Root: HKCU; Subkey: "Software\Classes\Drive\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Очистить свободное место"; Languages: russian; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Drive\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "MUIVerb"; ValueData: "Clean free space"; Languages: english; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Drive\shell\Nkardaz.SDeleteGUI"; ValueType: string; \
    ValueName: "Icon"; ValueData: "{app}\{#MyAppExeName}"; \
    Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Drive\shell\Nkardaz.SDeleteGUI\command"; ValueType: string; \
    ValueData: """{app}\{#MyAppExeName}"" %V"; \
    Flags: uninsdeletekey
